name: Metadata_WorkFlow 
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - Name: Get context
        runs: echo "${{ toJSON(github) }}"
